baseURL = "/"
languageCode = "en-us"
title = "Andraž Bajt's blog"
disableKinds = ["section"]
theme = "minimal"
copyright = "Andraz Bajt"
paginate = 20

[params]
    github = "edofic"
    linkedin = "edofic"
    twitter = "edofic"
    email = "blog@edofic.com"

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/"
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about"

[author]
    name = "Andraz Bajt"
