baseURL = "/"
languageCode = "en-us"
title = "Andraž Bajt's blog"
disableKinds = ["section"]
theme = "diary"
copyright = "Andraz Bajt"

[params]
    github = "edofic"
    linkedin = "edofic"
    twitter = "edofic"
    email = "edofic@edofic.com"

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/"
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about"

[author]
    name = "Andraz Bajt"
