baseURL = "https://edofic.com"
languageCode = "en-us"
title = "My Programming Escapades"
disableKinds = ["section"]
theme = "diary"
copyright = "Andraz Bajt"

[params]
    subtitle = "Andraz Bajt"
    github = "edofic"
    linkedin = "edofic"
    twitter = "edofic"
    email = "edofic@edofic.com"

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    title = "Blog Archive"
    url = "/"
    weight = -110

[author]
    name = "Andraz Bajt"
