baseURL: "/"
languageCode: "en-us"
title: "Andraž Bajt's blog"
disableKinds: ["section"]
copyright: "Andraz Bajt"
paginate: 20
enableEmoji: true

author:
    name: "Andraz Bajt"

params:
    github: "edofic"
    linkedin: "edofic"
    twitter: "edofic"
    email: "blog@edofic.com"

menu:
  main:
  - identifier: "archive"
    name: "Archive"
    url: "/"
  - identifier: "about"
    name: "About Me"
    url: "/about"

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    tabWidth: 2
